### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by EricBorland** [mTRx0/react-native-passkey#4]
Hi there,

First of all, thank you very much for developing this in such a short time since APIs are released, it definitely has a long life to live!

I was trying it today on an expo-based app and I had issues directly after installing the library. Of course, I didn't do the pod install since it's an Expo Go managed project, this is the error I got:

![Screen Shot 2022-12-21 at 17 29 52](https://user-images.githubusercontent.com/6512144/208955716-04b8b38e-7d6e-4135-ab6c-bc42fdcc1d93.png)

Would that be added in the near future?

Thanks.

Eric.

**Comment by mTRx0** [comment]
Hi Eric!

Unfortunately Expo Go doesn't support the usage of native modules that are not already included in the Expo SDK (custom native code), so there is no way for me to add support for it in this project.

Your best options would probably be to either use development builds or switch to a bare workflow with `expo prebuild`. You can read more about it [here](https://docs.expo.dev/workflow/customizing/).

I'm gonna close this issue but feel free to reach out if you encounter any other problems!

**Comment by armanmamyan** [comment]
@f-23 do you have any updates on whether or not the symbiosis with Expo GO is possible now?
